name: Deken Upload
on:
  workflow_dispatch:
    inputs:
      LibraryVersion:
        description: 'Add the version for upload'
        type: string
        required: true

jobs:
  deken-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Deken
        run: |
          git clone https://github.com/pure-data/deken.git

      - name: Make Folder for Upload
        run: |
          mkdir deken/developer/orchidea
          mkdir deken/developer/orchidea/src
          mkdir deken/developer/orchidea/help
          cp -r src/ deken/developer/orchidea/
          cp -r help/ deken/developer/orchidea/
          cp -r README.deken.pd deken/developer/orchidea/
          cp -r orchidea.py deken/developer/orchidea/
          cp -r README.md deken/developer/orchidea/
      
      - name: Set config for deken
        run: |
          mkdir -p ~/.deken && touch ~/.deken/config
          echo "username = ${{ secrets.DekenUsername }}" >> ~/.deken/config
          echo "password = ${{ secrets.DekenPassword }}" >> ~/.deken/config

      - name: Build and Upload Package
        run: |
          cd deken/developer/
          ./deken install --self
          ./deken package orchidea -v ${{ github.event.inputs.LibraryVersion }} -n orchidea
          ./deken upload *.dek
        continue-on-error: true

      - name: Upload package
        run: |
          cd deken/developer/
          ./deken upload *.dek

        
