name: Deken Upload
on:
  workflow_dispatch:
    inputs:
      LibraryVersion:
        description: 'Add the version for upload'
        type: string
        required: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Deken
        run: |
          git clone https://github.com/pure-data/deken.git

      - name: Make Folder for Upload
        run: |
          mkdir deken/developer/orchidea
          mkdir deken/developer/orchidea/instruments
          cp -r instruments/ deken/developer/orchidea/
          cp -r README.deken.pd deken/developer/orchidea/
          cp -r orchidea.py deken/developer/orchidea/
          cp -r README.md deken/developer/orchidea/

      - name: Set config for deken
        run: |
          mkdir -p ~/.deken && touch ~/.deken/config
          echo "username = charlesneimog" >> ~/.deken/config
          echo "password = ${{ secrets.DekenPassword }}" >> ~/.deken/config

      
      - name: Build and Upload Package
        run: |
          cd deken/developer/
          ./deken install --self
          ./deken package orchidea -v ${{ github.event.inputs.LibraryVersion }} -n orchidea
          ./deken upload *.dek

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        
        with:
          name: orchidea
          path: deken/developer/*.dek
        
