name: Deken Upload
on:
  workflow_dispatch:
    inputs:
      LibraryVersion:
        description: 'Add the version for upload'
        type: string
        required: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Deken
        run: |
          sudo apt install deken

      - name: Build and Upload Package
        run: |
          deken package . -v ${{ github.event.inputs.LibraryVersion }} -n orchidea
          deken upload *.dek
